- os_port_info:
    filters:
      name: "{{ int_swp }}"    
  register: port_info

- name: Configure router
      shell: |
        cat >> /etc/network/interfaces << EOF
        auto swp1
        iface swp1
            address {{ port_info.openstack_ports[0].fixed_ips[0].ip_address }}/24
            broadcast 192.168.2.255
        EOF
        ifreload -a
        ip route add default via {{ port_info.openstack_ports[0].fixed_ips[0].ip_address }} dev swp1 table 10
        cat >> /etc/cumulus/switchd.conf << EOF
        nat.dynamic_enable = TRUE
        nat.static_enable = TRUE
        EOF
        cat > /etc/default/isc-dhcp-server << EOF
        DHCPD_CONF="-cf /etc/dhcp/dhcpd.conf"
        DHCPD_PID="-pf /etc/dhcp/dhcpd.pid"
        INTERFACES="swp1"
        EOF
        cat > /etc/dhcp/dhcpd.conf << EOF
        default-lease-time 600;
        max-lease-time 7200;
        ddns-update-style none;
        authoritative;
        EOF
        
