- name: Configure router
      shell: |
        cat >> /etc/network/interfaces << EOF
        auto swp1
        iface swp1
            address 192.168.2.1/24
            broadcast 192.168.2.255
        EOF
        ifreload -a
        cat > /etc/dhcp/dhcpd.conf << EOF
        default-lease-time 600;
        max-lease-time 7200;
        ddns-update-style none;
        authoritative;
        subnet 192.168.2.0 netmask 255.255.255.0 {
            option routers 192.168.2.1;
            option broadcast-address 192.168.2.255;
            range 192.168.2.30 192.168.2.200;
        }
        host server_1 {
            hardware ethernet fa:16:3e:dd:19:71;
            fixed-address 192.168.2.10;
        }
        host server_2 {
            hardware ethernet fa:16:3e:60:48:47;
            fixed-address 192.168.2.11;
        }
        EOF
        cat > /etc/default/isc-dhcp-server << EOF
        DHCPD_CONF="-cf /etc/dhcp/dhcpd.conf"
        DHCPD_PID="-pf /etc/dhcp/dhcpd.pid"
        INTERFACES="swp1"
        EOF
        systemctl start dhcpd.service
        ifconfig eth0:1 10.100.160.10 netmask 255.255.255.0
        ifconfig eth0:2 10.100.160.11 netmask 255.255.255.0
        cat >> /etc/cumulus/switchd.conf << EOF
        nat.dynamic_enable = TRUE
        nat.static_enable = TRUE
        EOF
        systemctl restart switchd.service
        net add nat static snat tcp 192.168.2.10 translate 10.100.160.10
        net add nat static dnat tcp 10.100.160.10 translate 192.168.2.10
        net add nat static snat udp 192.168.2.10 translate 10.100.160.10
        net add nat static dnat udp 10.100.160.10 translate 192.168.2.10
        net add nat static snat icmp 192.168.2.10 translate 10.100.160.10
        net add nat static dnat icmp 10.100.160.10 translate 192.168.2.10
        net add nat static snat tcp 192.168.2.11 translate 10.100.160.11
        net add nat static dnat tcp 10.100.160.11 translate 192.168.2.11
        net add nat static snat udp 192.168.2.11 translate 10.100.160.11
        net add nat static dnat udp 10.100.160.11 translate 192.168.2.11
        net add nat static snat icmp 192.168.2.11 translate 10.100.160.11
        net add nat static dnat icmp 10.100.160.11 translate 192.168.2.11
        net commit
        ip rule add to 192.168.2.10 table 10
        ip rule add to 192.168.2.11 table 10
        ip route add default via 192.168.2.1 dev swp1 table 10
