(GET_INPUT, GET_PROPERTY, GET_ATTRIBUTE, GET_OPERATION_OUTPUT, GET_NODES_OF_TYPE, GET_ARTIFACT) \
    = ('get_input', 'get_property', 'get_attribute', 'get_operation_output', 'get_nodes_of_type', 'get_artifact')
GET_FUNCTIONS = (GET_INPUT, GET_PROPERTY, GET_ATTRIBUTE, GET_OPERATION_OUTPUT, GET_NODES_OF_TYPE, GET_ARTIFACT)

(SELF, SOURCE, SOURCES, TARGET, TARGETS, HOST) \
    = ('SELF', 'SOURCE', 'SOURCES', 'TARGET', 'TARGETS', 'HOST')
TEMPLATE_REFERENCES = (SELF, SOURCE, SOURCES, TARGET, TARGETS, HOST)