- os_port_facts:
    filters:
      name: "{{ int_swp }}"    
  register: port_info
  delegate_to: 127.0.0.1
  
- debug:
    msg: "{{ port_info.ansible_facts.openstack_ports[0].fixed_ips[0].ip_address }}/{{ ansible_default_ipv4.netmask }}"
  register: ip_info
  delegate_to: 127.0.0.1
  
- name: Configure router
  shell: |
        cat >> /etc/network/interfaces << EOF
        auto swp1
        iface swp1
            address {{ ip_info.msg |  ipaddr('address/prefix') }}
            broadcast {{ ip_info.msg |  ipaddr('broadcast') }}
        EOF
        ifreload -a
        ip route add default via {{ ip_info.msg | ipaddr('address') }} dev swp1 table 10
        cat >> /etc/cumulus/switchd.conf << EOF
        nat.dynamic_enable = TRUE
        nat.static_enable = TRUE
        EOF
        cat > /etc/default/isc-dhcp-server << EOF
        DHCPD_CONF="-cf /etc/dhcp/dhcpd.conf"
        DHCPD_PID="-pf /etc/dhcp/dhcpd.pid"
        INTERFACES="swp1"
        EOF
        cat > /etc/dhcp/dhcpd.conf << EOF
        default-lease-time 600;
        max-lease-time 7200;
        ddns-update-style none;
        authoritative;
        subnet {{ ip_info.msg |  ipaddr('network') }} netmask {{ ansible_default_ipv4.netmask }} {
            option routers {{ ip_info.msg | ipaddr('address') }};
            option broadcast-address {{ ip_info.msg |  ipaddr('broadcast') }};
            range {{ ip_info.msg | ipaddr('next_usable') }} {{ ip_info.msg | ipaddr('last_usable') }};
        }
        EOF
  become: yes
        
