- hosts: localhost
  vars:
    target_addr: "192.168.45.100"
  tasks:
  - os_subnets_facts:
    register: result
  - set_fact:
      network_cidr: '{{ item.cidr }}'
    with_items: "{{ result.ansible_facts.openstack_subnets }}"
    when: item.cidr == "{{ target_addr | ansible.netcommon.ipsubnet(item.cidr | ansible.netcommon.ipaddr('prefix')) }}"
  - debug:
      msg: "{{ network_cidr }}"
      

