# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\"\x80\x02\n\rClouniRequest\x12\x1d\n\x15template_file_content\x18\x01 \x01(\t\x12\x14\n\x0c\x63luster_name\x18\x02 \x01(\t\x12\x15\n\rvalidate_only\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65lete\x18\x04 \x01(\x08\x12\x10\n\x08provider\x18\x05 \x01(\t\x12\x1a\n\x12\x63onfiguration_tool\x18\x06 \x01(\t\x12\r\n\x05\x61sync\x18\x07 \x01(\x08\x12(\n\x05\x65xtra\x18\x08 \x03(\x0b\x32\x19.ClouniRequest.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9f\x01\n\x0e\x43louniResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.ClouniResponse.Status\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"E\n\x06Status\x12\x12\n\x0eTEMPLATE_VALID\x10\x00\x12\x14\n\x10TEMPLATE_INVALID\x10\x01\x12\x06\n\x02OK\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\x35\n\x06\x43louni\x12+\n\x06\x43louni\x12\x0e.ClouniRequest\x1a\x0f.ClouniResponse\"\x00\x62\x06proto3'
)



_CLOUNIRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ClouniResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEMPLATE_VALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TEMPLATE_INVALID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=363,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_CLOUNIRESPONSE_STATUS)


_CLOUNIREQUEST_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='ClouniRequest.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ClouniRequest.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ClouniRequest.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=270,
)

_CLOUNIREQUEST = _descriptor.Descriptor(
  name='ClouniRequest',
  full_name='ClouniRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_file_content', full_name='ClouniRequest.template_file_content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='ClouniRequest.cluster_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validate_only', full_name='ClouniRequest.validate_only', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete', full_name='ClouniRequest.delete', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='provider', full_name='ClouniRequest.provider', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration_tool', full_name='ClouniRequest.configuration_tool', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra', full_name='ClouniRequest.extra', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CLOUNIREQUEST_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=270,
)


_CLOUNIRESPONSE = _descriptor.Descriptor(
  name='ClouniResponse',
  full_name='ClouniResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ClouniResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='ClouniResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='ClouniResponse.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLOUNIRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=432,
)

_CLOUNIREQUEST_EXTRAENTRY.containing_type = _CLOUNIREQUEST
_CLOUNIREQUEST.fields_by_name['extra'].message_type = _CLOUNIREQUEST_EXTRAENTRY
_CLOUNIRESPONSE.fields_by_name['status'].enum_type = _CLOUNIRESPONSE_STATUS
_CLOUNIRESPONSE_STATUS.containing_type = _CLOUNIRESPONSE
DESCRIPTOR.message_types_by_name['ClouniRequest'] = _CLOUNIREQUEST
DESCRIPTOR.message_types_by_name['ClouniResponse'] = _CLOUNIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClouniRequest = _reflection.GeneratedProtocolMessageType('ClouniRequest', (_message.Message,), {

  'ExtraEntry' : _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLOUNIREQUEST_EXTRAENTRY,
    '__module__' : 'api_pb2'
    # @@protoc_insertion_point(class_scope:ClouniRequest.ExtraEntry)
    })
  ,
  'DESCRIPTOR' : _CLOUNIREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ClouniRequest)
  })
_sym_db.RegisterMessage(ClouniRequest)
_sym_db.RegisterMessage(ClouniRequest.ExtraEntry)

ClouniResponse = _reflection.GeneratedProtocolMessageType('ClouniResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOUNIRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ClouniResponse)
  })
_sym_db.RegisterMessage(ClouniResponse)


_CLOUNIREQUEST_EXTRAENTRY._options = None

_CLOUNI = _descriptor.ServiceDescriptor(
  name='Clouni',
  full_name='Clouni',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=434,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='Clouni',
    full_name='Clouni.Clouni',
    index=0,
    containing_service=None,
    input_type=_CLOUNIREQUEST,
    output_type=_CLOUNIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUNI)

DESCRIPTOR.services_by_name['Clouni'] = _CLOUNI

# @@protoc_insertion_point(module_scope)
